language: python

# safelist
branches:
  only:
  - gh-pages
  - master
  - Flatpak

addons:
  apt:
    packages:
    - fakeroot



matrix:
  include:
  - os: linux
    python: 3.8 # NOTE: on update, update also the var PYTHON_PATH in src/build-linux.sh
    dist: xenial
     cache:
      - pip
      - bundler
    env:
      - ARTISAN_OS=flatpak


install:
  - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
  - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py
  - chmod +x .travis/install-${ARTISAN_OS}.sh
  - .travis/install-${ARTISAN_OS}.sh

before_script:
  - ulimit -c unlimited -S
  - chmod +x .travis/script-${ARTISAN_OS}.sh

after_failure:
  - find .  -name "core*"
  - file src/core
  - gdb -c src/core `which python3` -ex "thread apply all bt" -ex "set pagination 0" -batch

script:
  - .travis/script-${ARTISAN_OS}.sh

after_success:
  - cd src
  - curl -L -O https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - export UPLOADTOOL_BODY="WARNING pre-release builds may not work. Use at your own risk."
  - if [ "$ARTISAN_OS" = "osx" ]; then bash upload.sh artisan*.dmg; fi
  - if [ "$ARTISAN_OS" = "rpi" ]; then bash upload.sh artisan*.deb; fi
  - if [ "$ARTISAN_OS" = "linux" ]; then bash upload.sh artisan*.rpm artisan*.deb; fi
  - if [ "$ARTISAN_OS" = "flatpak" ]; then bash upload.sh artisan*.flatpak; fi
